#%RAML 1.0 DataType
type: object
properties:
  id: 
    type: string
    example: "knd99"
  name: 
    type: string
    example: "some name"
  balance: 
    type: number
    example: 88.88
  status: 
    type: boolean
    example: true
 