#%RAML 1.0 DataType
type: object
properties:
  name:
    type: string
    example: "some name"
  balance:
    type: number
    example: 212
  status:
    type: boolean
    example: true
        
        
      